### ISSUE TITLE
Merge into upstream?

### ISSUE THREAD

**Issue by Neustradamus** [odedlaz/ax3600-files#5]
Hello @odedlaz,

Can you look forks?
- https://github.com/odedlaz/ax3600-files/network

@eisaev: Good to harmonize all?
- https://github.com/eisaev/ax3600-files/commits/master

**Comment by eisaev** [comment]
One note about my changes: `crash/crash_unlock.img` in my fork has been changed for the AC2350 model and this file needs to be either moved to another folder or renamed.

**Comment by odedlaz** [comment]
I can do that. A few questions:
1. why did you bump the python version to 3.7?
2. Can you explain the changes in this commit? these calculations should
work for AX1800+AX3600. Do they break for AC2350?
If they do, I can add a model directive.

https://github.com/eisaev/ax3600-files/commit/2c3e9afe1b3b2e3530eb90ba3e0ff525d81c67a9#diff-364c0caef5400e7d66152631df9cdf99b524c8e5340677a7c703e71aa5dd146dR105

**Comment by eisaev** [comment]
1. The python version has bumped because support for version 3.6 will end in December 2021 (see https://devguide.python.org/#status-of-python-branches).
2. 
- The old code broke on values containing the equality symbol:
```
-    header = dict((x.decode().split("=") for x in raw_header))
+    header = dict((x.decode().split("=", 1) for x in raw_header))
```
For example: `bootargs: board=AP152 console=ttyS0,115200  rootfstype=squashfs,jffs2 noinitrd miboot=firmware0 uart_en=0`
- The AC2350 uses a different byte order (big-endian vs little-endian). Because of this, the checksum in the output file must be written in reverse order:
```
-    new_raw_crc32 = bytes.fromhex(crc32.calculate(data_without_crc32)[len("0x"):])
+    new_raw_crc32 = bytes.fromhex(crc32.calculate(data_without_crc32)[len("0x"):])[::-1]
```
For example: `D0 9D 2B AD` vs `AD 2B 9D D0`

**Comment by odedlaz** [comment]
Got it. I’ll rebase the changes and add a flag indicating the model so
we’ll be able to create model-specific code-paths (like byte-order, etc’)

**Comment by odedlaz** [comment]
@eisaev , I wasn't able to rebase since  I wanted to introduce more changes. Can you please take a look at https://github.com/odedlaz/ax3600-files/commit/7a958c1387eaf336c323537317aceb1e33d2d995, https://github.com/odedlaz/ax3600-files/commit/99dcd48db1944b3afa8d0b9dc06a297177cb5083 & https://github.com/odedlaz/ax3600-files/commit/346c7a623897155d465f979d60aa1ec34caffbca?

@Neustradamus, I've merged the above to master. They should take care of the issues you raised.
I'm closing this. Please open another issue if  I missed something!

Thanks everyone of contributing!!!!

**Comment by Neustradamus** [comment]
Hello all,

Have you an idea if there will have a PR for have AX3600 compatibility in OpenWrt?

**Comment by odedlaz** [comment]
@Neustradamus , not sure I follow. can you elaborate?

**Comment by Neustradamus** [comment]
@odedlaz: A PR to add support of AX3600 in OpenWrt:
- https://github.com/openwrt/openwrt
